### ISSUE TITLE
Modular content elements -> collections

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-generators-java#10]
Shouldn't this be a list?

```
case "modular_content" :
                    //It would be nice to inject a generated model here, but the information is not in the API
                    //consumer could always use .castTo() off the ContentItem
                    typeName = ClassName.get(ContentItem.class);
```

**Comment by petrsvihlik** [comment]
generating a single content item would make sense only if there was a constraint (of maximum 1 content items) set on the modular content element...which I don't think is currently possible to find out via the types api

**Comment by aweigold** [comment]
Good catch... I'll also review the SDK code to see if it's using the same consideration.
