### ISSUE TITLE
Publish gradle plugin to gradle plugin portal

### ISSUE THREAD

**Issue by aweigold** [Kentico/cloud-generators-java#3]
Publishing the gradle plugin to the portal will allow addition of the plugin to any gradle build with a one liner

https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/

**Comment by aweigold** [comment]
This process is pretty easy, and will reduce boilerplate code from a users gradle file.  The gradle plugin portal doesn't support SNAPSHOT publishing, nor deletion of them.  Will wait until a code review is done to create a release version 1.0 before doing this.

**Comment by petrsvihlik** [comment]
I think we're ready for the release.

**Comment by aweigold** [comment]
Complete: https://plugins.gradle.org/plugin/com.kenticocloud.generator

**Comment by petrsvihlik** [comment]
Perfect!
